package org.crazyit.drools;

rule "Test Insert"
	when
		$p : RHSPerson(age == 12 || age == 11)
	then
		System.out.println("insert处理对象：" + $p.getName());
		RHSPerson newPerson = new RHSPerson("new person", $p.getAge() + 1);
		insert(newPerson);
end

rule "Test update"
	when
		$p : RHSPerson(age == 20 || age == 21)
	then
		System.out.println("update处理对象：" + $p.getName());
		$p.setAge($p.getAge() + 1);
		update($p);
end
